export var example_cols = [
  {
    name: "col1",
    align: "center",
    label: "col1",
    field: "col1",
    sortable: true,
  },
  {
    name: "col2",
    align: "center",
    label: "col2",
    field: "col2",
    sortable: true,
  },
  {
    name: "col3",
    align: "center",
    label: "col3",
    field: "col3",
    sortable: true,
  },
  {
    name: "col4",
    align: "center",
    label: "col4",
    field: "col4",
    sortable: true,
  },
  {
    name: "col5",
    align: "center",
    label: "col5",
    field: "col5",
    sortable: true,
  },
  {
    name: "col6",
    align: "center",
    label: "col6",
    field: "col6",
    sortable: true,
  },
  {
    name: "col7",
    align: "center",
    label: "col7",
    field: "col7",
    sortable: true,
  },
  {
    name: "col8",
    align: "center",
    label: "col8",
    field: "col8",
    sortable: true,
  },
  {
    name: "col9",
    align: "center",
    label: "col9",
    field: "col9",
    sortable: true,
  },
  {
    name: "col10",
    align: "center",
    label: "col10",
    field: "col10",
    sortable: true,
  },
  {
    name: "action",
    align: "center",
    label: "Actions",
    field: "col10",
    sortable: true,
  },
];
export var example_cols_visible = [
  "col1",
  "col2",
  "col3",
  "col4",
  "col5",
  "col6",
  "col7",
  "col8",
  "col9",
  "col10",
  "action",
];
